name: go_router_playground
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  gap: ^3.0.1
  go_router: ^9.0.3
  intersperse: ^2.0.0
  recase: ^4.1.0
  simple_logger: ^1.9.0+2

dev_dependencies:
  build_runner: ^2.4.6
  build_verify: ^3.1.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.2.2
  pedantic_mono: ^1.23.0

flutter:
  uses-material-design: true
